### ISSUE TITLE
是否可增加有没中文语言标签？

### ISSUE THREAD

**Issue by snakwu** [ningxiaoxiao/NSGameDownloader#2]
是否可增加有没中文语言标签？

**Comment by ningxiaoxiao** [comment]
这个需求已经记录.有计划会增加更详细的管理功能
我现在正在增加直接下载功能.我认为直接下载功能.会比这个需求更重要,

**Comment by snakwu** [comment]
嗯，有道理，直接理载是加进air2？还是pandownload

**Comment by ningxiaoxiao** [comment]
加载到aria2c中, 
pandownload用的下载引擎也是aria2c

**Comment by snakwu** [comment]
期待你的新版啊!直接带下载,就炸天了!
