### ISSUE TITLE
“保存至网盘”显示页面异常，且无法成功保存nsp文件

### ISSUE THREAD

**Issue by nov12** [ningxiaoxiao/NSGameDownloader#3]
win10

保存至网盘只能保存xci文件，nsp本体及补丁就会保存失败。

**Comment by ningxiaoxiao** [comment]
哪个版本?
一直出现,还是个例?

**Comment by snakwu** [comment]
0.8版本，我也同样遇到

**Comment by ningxiaoxiao** [comment]
保存页面显示错误这个是已知的.不知道怎么回事.IE有时会没有正常加载CSS文件. 
解决办法就是要刷新一下.或者把程序窗口拉大. 可以看到下面有一个保存.
NSP 保存失败,已经找到原因了.正在修复

**Comment by ningxiaoxiao** [comment]
已经在0.9版本修复
