### ISSUE TITLE
[BUG] UPD+DLC的网址错误，无法正确显示、复制

### ISSUE THREAD

**Issue by nov12** [ningxiaoxiao/NSGameDownloader#4]
[BUG] UPD+DLC的网址错误，无法正确显示及复制，只能在页面右键——属性，复制网页地址才可以。

**Comment by nov12** [comment]
例如:尤库小岛之旅
https://pan.baidu.com/s/1tOFTvpJwikcdo2W12Z8dEw#list/path=/Nintendo Switch Games/UPD   DLC/01000/010002D00632E000&parentPath=/

漏了一个“+”号

**Comment by ningxiaoxiao** [comment]
已经在0.9版本修复
